apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: notabee-backend
  name: notabee-backend
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: notabee-backend
status:
  loadBalancer: {}
