apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: notabee-mysql
  name: notabee-mysql
spec:
  ports:
    - name: http
      port: 3306
      targetPort: 3306
  selector:
    app: notabee-mysql
status:
  loadBalancer: {}
