apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: notabee-frontend
  name: notabee-frontend
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: notabee-frontend
status:
  loadBalancer: {}
